apiVersion: apps/v1
kind: Deployment
metadata:
  name: packu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: packu
  template:
    metadata:
      labels:
        name: packu
    spec:
      serviceAccountName: packu
      containers:
        - name: packu
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - packu
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "packu"
