kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: packu
subjects:
- kind: ServiceAccount
  name: packu
roleRef:
  kind: Role
  name: packu
  apiGroup: rbac.authorization.k8s.io
